FROM --platform=linux/amd64 golang:alpine AS build
RUN apk add --no-cache gcc musl-dev
WORKDIR /build
COPY . ./
RUN CGO_ENABLED=1 CC=gcc GOOS=linux GOARCH=amd64 go build -o bin/server .

FROM --platform=linux/amd64 alpine:latest AS server
RUN mkdir -p /usr/echovault/bin
COPY --from=build /build/bin/server /usr/echovault/bin
WORKDIR /usr/echovault/bin
ENTRYPOINT ["./server"]