FROM --platform=linux/amd64 alpine:latest

RUN mkdir -p /usr/local/lib/echovault
RUN mkdir -p /opt/echovault/bin
RUN mkdir -p /etc/ssl/certs/echovault/echovault
RUN mkdir -p /etc/ssl/certs/echovault/client

COPY ./bin/linux/x86_64/server /opt/echovault/bin
COPY ./openssl/server /etc/ssl/certs/echovault/server
COPY ./openssl/client /etc/ssl/certs/echovault/client

WORKDIR /opt/echovault/bin

CMD "./server" \
  "--bind-addr" "${BIND_ADDR}" \
  "--port" "${PORT}" \
  "--memberlist-port" "${ML_PORT}" \
  "--raft-port" "${RAFT_PORT}" \
  "--server-id" "${SERVER_ID}" \
  "--join-addr" "${JOIN_ADDR}" \
  "--data-dir" "${DATA_DIR}" \
  "--snapshot-threshold" "${SNAPSHOT_THRESHOLD}" \
  "--snapshot-interval" "${SNAPSHOT_INTERVAL}" \
  "--max-memory" "${MAX_MEMORY}" \
  "--eviction-policy" "${EVICTION_POLICY}" \
  "--eviction-sample" "${EVICTION_SAMPLE}" \
  "--eviction-interval" "${EVICTION_INTERVAL}" \
  "--tls=${TLS}" \
  "--mtls=${MTLS}" \
  "--bootstrap-cluster=${BOOTSTRAP_CLUSTER}" \
  "--acl-config=${ACL_CONFIG}" \
  "--require-pass=${REQUIRE_PASS}" \
  "--password=${PASSWORD}" \
  "--forward-commands=${FORWARD_COMMAND}" \
  "--restore-snapshot=${RESTORE_SNAPSHOT}" \
  "--restore-aof=${RESTORE_AOF}" \
  "--aof-sync-strategy=${AOF_SYNC_STRATEGY}" \
  # List of echovault cert/key pairs
  "--cert-key-pair=${CERT_KEY_PAIR_1}" \
  "--cert-key-pair=${CERT_KEY_PAIR_2}" \
  # List of client certs
  "--client-ca=${CLIENT_CA_1}" \
  # List of plugins to load on startup
  "--loadmodule=${MODULE_1}" \
  "--loadmodule=${MODULE_2}" \
