# run from root dir
services:
  test:
    build: 
      context: ..
      dockerfile: windows_test_env/Dockerfile
    container_name: sugardb_win_test_env
    volumes:
      - ../coverage/coverage.out:/testspace/coverage/coverage.out
    stdin_open: true
    tty: true

